// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
   if (kIsWeb) {
  return web;
}

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2H0ZVcx_2XopvDHdLXlFCrICOEKDZ8E',
    appId: '1:861108055766:android:8822ed97b54b1fac2be377',
    messagingSenderId: '861108055766',
    projectId: 'projetflutter-cfd38',
    storageBucket: 'projetflutter-cfd38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxlSO8rYmYsi66LG0Dlk8DlHJ0PkshKE',
    appId: '1:861108055766:ios:f14797ec8754a2822be377',
    messagingSenderId: '861108055766',
    projectId: 'projetflutter-cfd38',
    storageBucket: 'projetflutter-cfd38.firebasestorage.app',
    iosBundleId: 'com.example.projetflutter',
  );

static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyASTqLhZOAKaBKUxUqwYFxDZCtTHLYsRRA",
  authDomain: "projetflutter-cfd38.firebaseapp.com",
  projectId: "projetflutter-cfd38",
  storageBucket: "projetflutter-cfd38.firebasestorage.appspot.com",
  messagingSenderId: "861108055766",
  appId: "1:861108055766:web:43ae775bedde94222be377",
);

}